---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 13.6.4

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9.4
  - name: centos-7.4
  - name: centos-6.9
  - name: fedora-27

suites:
  - name: default
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
