---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.2.0
  install_strategy: always
  attributes:
    motd_chef_status:
      server_owner: 'Fake Dept. (fake@fake.org)'

verifier:
  name: inspec

# Every bento box supported by Chef 14
platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-i386
  - name: ubuntu-14.04
  - name: ubuntu-14.04-i386
  - name: ubuntu-12.04
  - name: ubuntu-12.04-i386
  - name: debian-9.5
  - name: debian-9.5-i386
  - name: debian-8.11
  - name: debian-8.10-i386
  - name: debian-7.11
  - name: debian-7.11-i386
  - name: centos-7.5
  - name: centos-6.10
  - name: centos-6.10-i386
  - name: centos-5.11
  - name: centos-5.11-i386
  - name: oracle-7.5
  - name: oracle-6.10
  - name: oracle-6.10-i386
  - name: oracle-5.11
  - name: oracle-5.11-i386
  - name: fedora-28
  - name: fedora-27
  - name: fedora-26
  - name: gbailey/amzn2 # 2018.08
  - name: stakahashi/amazonlinux2 # 2017.12
  - name: realreadme/amazon2016.09
  - name: opensuse-leap-42.3
  - name: freebsd-11.2
  - name: freebsd-11.2-i386
  - name: freebsd-10.4
  - name: freebsd-10.4-i386
  - name: mwrock/Windows2016
    transport:
      name: winrm
  - name: a-mcf/Win2012R2-WMF5-min
    transport:
      name: winrm
  - name: salesforce/server2008r2
    transport:
      name: winrm

suites:
  - name: debian-based
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - ubuntu-16.04-i386
      - ubuntu-14.04
      - ubuntu-14.04-i386
      #- ubuntu-12.04 # Chef 13 dropped support
      #- ubuntu-12.04-i386 # Chef 13 dropped support
      - debian-9.5
      - debian-9.5-i386
      - debian-8.11
      - debian-8.10-i386
      #- debian-7.11 # Ruby requires GLIBC
      #- debian-7.11-i386 # Ruby requires GLIBC
  - name: rhel-based
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      - centos-7.5
      - centos-6.10
      - centos-6.10-i386
      #- centos-5.11 # Chef 14 dropped support
      #- centos-5.11-i386 # Chef 14 dropped support
      - oracle-7.5
      - oracle-6.10
      - oracle-6.10-i386
      #- oracle-5.11 # Chef 14 dropped support
      #- oracle-5.11-i386 # Chef 14 dropped support
      - fedora-28
      - fedora-27
      - fedora-26
  - name: all-others
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    includes:
      #- gbailey/amzn2 # Omnibus detection for Amazon 2 is currently broken
      #- stakahashi/amazonlinux2 # Omnibus detection for Amazon 2 is currently broken
      - realreadme/amazon2016.09
      - opensuse-leap-42.3
      #- freebsd-11.2 # freebsd has not been worth investigating
      #- freebsd-11.2-i386 # Chef package not found
      #- freebsd-10.4 # freebsd has not been worth investigating
      #- freebsd-10.4-i386 # Box does not exist
