---
driver:
  name: ec2
  region: us-west-1
  instance_type: t2.micro
  tags:
    Name: Chef Run Recorder
    Service: Infrastructure
    Environment: Test
    Fund: 103010
    Org: 60412
    Department: Systems Engineering

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.10.9
  install_strategy: always
  attributes:
    motd_chef_status:
      server_owner: 'Fake Dept. (fake@fake.org)'

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9
  - name: debian-8
  - name: centos-7
  - name: centos-6
  - name: oracle-7.6
  - name: oracle-6.10
  - name: fedora-29
  - name: fedora-28
  - name: amazon2
  - name: amazon-
  - name: sles-15
  - name: windows-2019
    driver:
      image_id: ami-087efd22b572d6bc1
    transport:
      name: winrm
  - name: windows-2016
    transport:
      name: winrm
  - name: windows-2012r2
    transport:
      name: winrm
  - name: windows-2008r2sp1
    transport:
      name: winrm

suites:
  - name: debian-based
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    includes:
      - ubuntu-18.04
      - ubuntu-16.04
      - ubuntu-14.04
      - debian-9
      - debian-8
  - name: rhel-based
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    includes:
      - centos-7
      - centos-6
      - oracle-7.6
      - oracle-6.10
      - fedora-29
      - fedora-28
  - name: all-others
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    includes:
      - amazon2
      - amazon-
      - sles-15
