AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.3
LineLength:
  Max: 120 # Default is 80
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
RedundantReturn:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
