AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0.1
  NewCops: enable
Layout/LineLength:
  Max: 120 # Default is 80
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/WordArray:
  EnforcedStyle: brackets
