---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 17.1.35
  install_strategy: once

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: debian-10
  - name: rhel-8
  - name: rhel-7
  - name: centos-8
  - name: oracle-8
  - name: fedora-33
  - name: amazon2
  - name: sles-15
  - name: windows-2019
  - name: windows-2016
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[motd_chef_status::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
    includes:
      - ubuntu-20.04
      - centos-8
